### ISSUE TITLE
about some training details

### ISSUE THREAD

**Issue by Yetaiheng** [Xiaojiu-z/Stable-Makeup#12]
Hello, thank you for your excellent work. I would like to inquire about some details. Regarding the training of the content encoder and the structure encoder ControlNet, you mentioned that you trained them using your own dataset. I would like to ask what the condition image and GT are for the content encoder, are they the source image and the image after makeup application, respectively? I am also curious about what the condition image and GT are for the structure encoder and how they are obtained. I hope to get your answers. By the way, I am also a student at SJTU.

**Comment by Xiaojiu-z** [comment]
> Hello, thank you for your excellent work. I would like to inquire about some details. Regarding the training of the content encoder and the structure encoder ControlNet, you mentioned that you trained them using your own dataset. I would like to ask what the condition image and GT are for the content encoder, are they the source image and the image after makeup application, respectively? I am also curious about what the condition image and GT are for the structure encoder and how they are obtained. I hope to get your answers. By the way, I am also a student at SJTU.

Hi, Taiheng. The content encoder and the structure encoder in ControlNet are trained in an end-to-end manner, meaning that all modules are integrated into the Unet during training. The condition image for the content encoder is the source image, while the condition image for the structure encoder is the facial structure image extracted from the same source image. The way to obtain all the images is described in my paper, and the codes are under the folder [datasets](https://github.com/Xiaojiu-z/Stable-Makeup/tree/main/datasets).
