### ISSUE TITLE
fp16 train.py version

### ISSUE THREAD

**Issue by ZhuangLii** [Xiaojiu-z/Stable-Makeup#13]
Great work, but when i try to use fp16 to train the model, it appears `ValueError: Attempting to unscale FP16 gradients` bug, could u help me to solve the bug.

**Comment by Xiaojiu-z** [comment]
> Great work, but when i try to use fp16 to train the model, it appears `ValueError: Attempting to unscale FP16 gradients` bug, could u help me to solve the bug.

Sorry, It's really hard to help you to solve this problem. You know, This error may happen in various ways and in some lines of your code.

**Comment by ZhuangLii** [comment]
Did you train using fp16? I only modified the input data part, which shouldn't cause that bug.

**Comment by Xiaojiu-z** [comment]
> Did you train using fp16? I only modified the input data part, which shouldn't cause that bug.

Oh, I get your means. The training code hasn't been adapted for fp16 training. I thought you had adapted the code by yourself. Besides,  I have no spare time to update it. Maybe you can do it yourself.

**Comment by ZhuangLii** [comment]
Okay, thank you for your reply.
