### ISSUE TITLE
util packet error problem

### ISSUE THREAD

**Issue by homexjh** [Xiaojiu-z/Stable-Makeup#14]
Did you write this utils package by yourself? The folder does not have this utils package. I installed the dependency of utils, but still an error was reported. ModuleNotFoundError: No module named 'utils.pipeline_sd15'

**Comment by Dratlan** [comment]
Hey bro. have you solved it, I got the same problem

**Comment by JosephNgD** [comment]
You can fix this problem by replacing `utils.pipeline_sd15` with `pipeline_sd15`.
