### ISSUE TITLE
No text prompt?

### ISSUE THREAD

**Issue by Sylvie-X** [Xiaojiu-z/Stable-Makeup#16]
As mentioned in paper, there can be original text input, KV head fixed. But here is no text prompt input in your codes, which makes me confused.

**Comment by JAJASONW** [comment]
Hello, I also have this confusion. Have you solved this problem now? Thank you

**Comment by Xiaojiu-z** [comment]
> As mentioned in paper, there can be original text input, KV head fixed. But here is no text prompt input in your codes, which makes me confused.

You can simply achieve it by setting 0 to the number of scale for each ControlNet part and using original text prompt cross-attn.
