### ISSUE TITLE
makeup_encoder using image_encoder_l

### ISSUE THREAD

**Issue by ProtoZenon123** [Xiaojiu-z/Stable-Makeup#18]
I downloaded openai/clip-vit-large-patch14 and put it in ../models/image_encoder_l.
I trying to run infer_kps.py and get this problem:

File "infer_kps.py", line 54, in <module>
    makeup_encoder = detail_encoder(Unet, "./models/image_encoder_l", "cuda", dtype=torch.float32)
...
    ../lib/python3.8/site-packages/transformers/modeling_utils.py", line 585, in load_state_dict
    raise OSError(
OSError: You seem to have cloned a repository without having git-lfs installed. Please install git-lfs and run `git lfs install` followed by `git lfs pull` in the folder you cloned.

I follow this instruction, installed git-lfs, ran `git lfs install` with notification: 
Updated git hooks.
Git LFS initialized.
Then I ran `git lfs pull` with no notification and get the same error when try running infer_kps.py again.
how can I solve this issue

**Comment by Xiaojiu-z** [comment]
You can easily use Huggingface webpage to download it. (just click the download while not use git)
