### ISSUE TITLE
result images

### ISSUE THREAD

**Issue by trnhong193** [Xiaojiu-z/Stable-Makeup#19]
I have tried multiple times with infer_kps and I noticed that the model works quite well with images that have very large and very dark stains, like the reference image of the joker, etc. I tried some images with similar stains but smaller in scope, and it seems like the model no longer produces the desired results (for example, I added a stain at the corner of the mouth, but the resulting image had no stain at all, just the lips with the correct color similar to the reference image). Is there any way to improve this, please?

**Comment by Xiaojiu-z** [comment]
> I have tried multiple times with infer_kps and I noticed that the model works quite well with images that have very large and very dark stains, like the reference image of the joker, etc. I tried some images with similar stains but smaller in scope, and it seems like the model no longer produces the desired results (for example, I added a stain at the corner of the mouth, but the resulting image had no stain at all, just the lips with the correct color similar to the reference image). Is there any way to improve this, please?

In my opinion, The same structure with a better dataset can significantly improve it ~
