### ISSUE TITLE
How can I implement t2i stable makeup?

### ISSUE THREAD

**Issue by leehwalmin** [Xiaojiu-z/Stable-Makeup#20]
Embedding dimension of text prompt is 768 and makeup image is 1024. How can I tune the encoder_hidden_states to combine these two inputs?

**Comment by Xiaojiu-z** [comment]
> Embedding dimension of text prompt is 768 and makeup image is 1024. How can I tune the encoder_hidden_states to combine these two inputs?

Calculate text attention and makeup attention, and then add these 2 outputs. (like IP-adapter)

**Comment by Dratlan** [comment]
> > Embedding dimension of text prompt is 768 and makeup image is 1024. How can I tune the encoder_hidden_states to combine these two inputs?
> 
> Calculate text attention and makeup attention, and then add these 2 outputs. (like IP-adapter)
@Xiaojiu-z It seems your code have finished this, In diffusers/models/unet_2d_condition.py, the "encoder_hid_dim_type" got 3 kinds {text_proj,image_proj,text_image_proj}, and i think it according to t2i/i2i/t&i2i stable makeup. maybe you can provide simple usage for this three kind.
