### ISSUE TITLE
关于制作数据集的问题

### ISSUE THREAD

**Issue by kr150** [Xiaojiu-z/Stable-Makeup#24]
在**readme**中我看到您说的each line with 4 key-value pairs, including **original id**, **edited id**, **augmented id**, **face structural image of edited id**，初步理解为**原始图像**，**文本反演后图像**，**对原始图像进行增强后的图像**，以及**文本反演后面部结构图**

但是在代码中我看到您将数据分为**id_pixel_values**,**warp_pixel_values**,**makeup_pixel_values**,**pose_pixel_values**,这里的**warp_pixel_values**

我看到是用在**makeup_encoder**这一步中，按照论文理解我以为是对文本反演后图像进行增强之后的图像称为

**warp_pixel_values**，但是看到您在**preprocess_train（exampls）**这个函数中就已经对id_pixel_values,pose_pixel_values ,makeup_pixel_values作了数据增强，所以想请问**warp_pixel_values**是怎么的来的

**Comment by yangzi1104** [comment]
@kr150 请问训练完成了吗，想看看你的数据集示例

**Comment by kr150** [comment]
> @kr150 请问训练完成了吗，想看看你的数据集示例

我的训练不太完善，数据集包含三个：原始图像，ledits编辑后的图像，以及在编辑后的图像上提取的面部线条

**Comment by kr150** [comment]
我的训练不太完善，数据集包含三个：原始图像，ledits编辑后的图像，以及在编辑后的图像上提取的面部线条
在训练过程中makeup_pixel_values和warp_pixel_values都采用ledits编辑后的图像

**Comment by kr150** [comment]
> @kr150 请问训练完成了吗，想看看你的数据集示例

我的训练不太完善，数据集包含三个：原始图像，ledits编辑后的图像，以及在编辑后的图像上提取的面部线条
在训练过程中makeup_pixel_values和warp_pixel_values都采用ledits编辑后的图像

**Comment by Xiaojiu-z** [comment]
> 在**readme**中我看到您说的each line with 4 key-value pairs, including **original id**, **edited id**, **augmented id**, **face structural image of edited id**，初步理解为**原始图像**，**文本反演后图像**，**对原始图像进行增强后的图像**，以及**文本反演后面部结构图**
> 
> 但是在代码中我看到您将数据分为**id_pixel_values**,**warp_pixel_values**,**makeup_pixel_values**,**pose_pixel_values**,这里的**warp_pixel_values**
> 
> 我看到是用在**makeup_encoder**这一步中，按照论文理解我以为是对文本反演后图像进行增强之后的图像称为
> 
> **warp_pixel_values**，但是看到您在**preprocess_train（exampls）这个函数中就已经对id_pixel_values,pose_pixel_values ,makeup_pixel_values作了数据增强，所以想请问warp_pixel_values**是怎么的来的

我使用这个[库](https://github.com/yaopang/FaceMorpher/tree/master)添加一些随机扰动到每个面部关键点，如鼻子，眼睛和脸。我把源代码留在了上一家公司，所以没有公开，但是实现非常简单，GPT可以帮助你实现它。

**Comment by kr150** [comment]
> > 在**readme**中我看到您说的each line with 4 key-value pairs, including **original id**, **edited id**, **augmented id**, **face structural image of edited id**，初步理解为**原始图像**，**文本反演后图像**，**对原始图像进行增强后的图像**，以及**文本反演后面部结构图**
> > 但是在代码中我看到您将数据分为**id_pixel_values**,**warp_pixel_values**,**makeup_pixel_values**,**pose_pixel_values**,这里的**warp_pixel_values**
> > 我看到是用在**makeup_encoder**这一步中，按照论文理解我以为是对文本反演后图像进行增强之后的图像称为
> > **warp_pixel_values**，但是看到您在**preprocess_train（exampls）这个函数中就已经对id_pixel_values,pose_pixel_values ,makeup_pixel_values作了数据增强，所以想请问warp_pixel_values**是怎么的来的
> 
> 我使用这个[库](https://github.com/yaopang/FaceMorpher/tree/master)添加一些随机扰动到每个面部关键点，如鼻子，眼睛和脸。我把源代码留在了上一家公司，所以没有公开，但是实现非常简单，GPT可以帮助你实现它。

我看到代码中写的是1000epoch，这也太吓人了，即使是8张V100这也得跑上百天吧。我用单张a100，30个epoch需要96小时

**Comment by Xiaojiu-z** [comment]
> > > 在**readme**中我看到您说的each line with 4 key-value pairs, including **original id**, **edited id**, **augmented id**, **face structural image of edited id**，初步理解为**原始图像**，**文本反演后图像**，**对原始图像进行增强后的图像**，以及**文本反演后面部结构图**
> > > 但是在代码中我看到您将数据分为**id_pixel_values**,**warp_pixel_values**,**makeup_pixel_values**,**pose_pixel_values**,这里的**warp_pixel_values**
> > > 我看到是用在**makeup_encoder**这一步中，按照论文理解我以为是对文本反演后图像进行增强之后的图像称为
> > > **warp_pixel_values**，但是看到您在**preprocess_train（exampls）这个函数中就已经对id_pixel_values,pose_pixel_values ,makeup_pixel_values作了数据增强，所以想请问warp_pixel_values**是怎么的来的
> > 
> > 
> > 我使用这个[库](https://github.com/yaopang/FaceMorpher/tree/master)添加一些随机扰动到每个面部关键点，如鼻子，眼睛和脸。我把源代码留在了上一家公司，所以没有公开，但是实现非常简单，GPT可以帮助你实现它。
> 
> 我看到代码中写的是1000epoch，这也太吓人了，即使是8张V100这也得跑上百天吧。我用单张a100，30个epoch需要96小时

哈哈，训练可以提前停止，大概在5w-10w steps左右就能看到效果。

**Comment by BugsMaker0513** [comment]
> > 在**readme**中我看到您说的each line with 4 key-value pairs, including **original id**, **edited id**, **augmented id**, **face structural image of edited id**，初步理解为**原始图像**，**文本反演后图像**，**对原始图像进行增强后的图像**，以及**文本反演后面部结构图**
> > 但是在代码中我看到您将数据分为**id_pixel_values**,**warp_pixel_values**,**makeup_pixel_values**,**pose_pixel_values**,这里的**warp_pixel_values**
> > 我看到是用在**makeup_encoder**这一步中，按照论文理解我以为是对文本反演后图像进行增强之后的图像称为
> > **warp_pixel_values**，但是看到您在**preprocess_train（exampls）这个函数中就已经对id_pixel_values,pose_pixel_values ,makeup_pixel_values作了数据增强，所以想请问warp_pixel_values**是怎么的来的
> 
> 我使用这个[库](https://github.com/yaopang/FaceMorpher/tree/master)添加一些随机扰动到每个面部关键点，如鼻子，眼睛和脸。我把源代码留在了上一家公司，所以没有公开，但是实现非常简单，GPT可以帮助你实现它。

请问这个具体思路是怎么样呢，这个库的作用是添加扰动，还是根据扰动后的关键点生成图片？

**Comment by kr150** [comment]
关注这个库中的这个功能：识别出两个人脸，然后利用A的关键点将人脸图像迁移到B的关键点上
然后利用这个方法，识别出A的关键点，然后在关键点上添加随机扰动，再将A人脸图像迁移到添加A‘上

**Comment by JiangThea** [comment]
@kr150  Please let me know if you can reproduce all the training data. If possible, could you share some examples? Thank you!
