### ISSUE TITLE
about clip image encoder

### ISSUE THREAD

**Issue by lh-13** [Xiaojiu-z/Stable-Makeup#4]
What should I use instead of clip image encoder? Because clip image encoder will reduce the reference image to 224*224, and some details may be last. 
so I wonder if there is a feature extrator with a higher resolution ?

**Comment by Xiaojiu-z** [comment]
> What should I use instead of clip image encoder? Because clip image encoder will reduce the reference image to 224*224, and some details may be last. so I wonder if there is a feature extrator with a higher resolution ?

Higher resolution results in higher computational overhead...... I believe one way to enhance the performance of an image encoder is to train its image restoration capabilities.
（Maybe you can develop a better feature extractor.）
