### ISSUE TITLE
Dataset

### ISSUE THREAD

**Issue by SongDaShuai** [Xiaojiu-z/Stable-Makeup#6]
Will the plans for the data set be made public

**Comment by Xiaojiu-z** [comment]
> Will the plans for the data set be made public

We're planning to make a better and larger dataset, and we'll make it public when we're done

**Comment by Jamie-Cheung** [comment]
> > Will the plans for the data set be made public
> 
> We're planning to make a better and larger dataset, and we'll make it public when we're done
Waiting

**Comment by Jian-Yin-Shine** [comment]
Hi, when do you plan to open the dataset? 💦💦💦

**Comment by Xiaojiu-z** [comment]
I just left my last company and I'm working on other projects. So..... You can easily get similar datasets using this pipeline: https://github.com/Xiaojiu-z/Stable-Makeup/blob/main/datasets/ledits_utils/ledits_cycle_for_debug.py.

**Comment by Jian-Yin-Shine** [comment]
How do you get the face mask of ffhq? Because the original ffhq dataset has no mask.

**Comment by kr150** [comment]
@Jian-Yin-Shine 您好，请问您复现出来数据集了吗，作者所说的 (each line with 4 key-value pairs, including original id, edited id, augmented id, face structural image of edited id) 中的augmented id对应代码中的warp_pixel_values是对编辑后的图像的数据增强后的图像是吗
