### ISSUE TITLE
using text prompts

### ISSUE THREAD

**Issue by trofimovaolga** [Xiaojiu-z/Stable-Makeup#8]
Hi, could you please explain how to use text prompts during inference? During training you don't use any text prompts and condition for unet is output vector from makeup_encoder. You can only condition the model with a makeup image, not a text, correct?

**Comment by Xiaojiu-z** [comment]
> Hi, could you please explain how to use text prompts during inference? During training you don't use any text prompts and condition for unet is output vector from makeup_encoder. You can only condition the model with a makeup image, not a text, correct?

Sorry, I forgot to organize this part of code ...... really busy now 😣...... you can simply achieve it by setting 0 to the number of scale for each ControlNet part and using original text prompt cross-attn.

**Comment by Dratlan** [comment]
> ,

Hi, have you figure it for using text prompts

**Comment by Dratlan** [comment]
@trofimovaolga

**Comment by trofimovaolga** [comment]
> > ,
> 
> Hi, have you figure it for using text prompts

Hi, sorry, I switched to something else so I can't help you

**Comment by Dratlan** [comment]
> > > ,
> > 
> > 
> > Hi, have you figure it for using text prompts
> 
> Hi, sorry, I switched to something else so I can't help you

what's that?
