### ISSUE TITLE
diffvg need python 3.7  py310 cant install

### ISSUE THREAD

**Issue by guahunyo** [Xiaojiu-z/Stable-Makeup#9]
It is best to write it clearly in the readme. This will save you the trouble of installing conda and having to reinstall the python environment.

**Comment by guahunyo** [comment]
ERROR: Ignored the following versions that require a different python version: 1.2.0 Requires-Python >=3.9; 1.2.1 Requires-Python >=3.9; 1.2.1rc1 Requires-Python >=3.9  

So how do I pretend to be

**Comment by guahunyo** [comment]
ERROR: Could not find a version that satisfies the requirement diffvg==0.0.1 (from versions: none)
ERROR: No matching distribution found for diffvg==0.0.1

**Comment by guahunyo** [comment]
I tried cuda 117 118 121
python 3.7 3.8 3.9 310
None of them depend on success.
Mainly because diffvg==0.0.1

**Comment by linhusyung** [comment]
It can run without installing diffvg.
